// vocab-lesson9.js
if (typeof window.allVocabulary === 'undefined') { window.allVocabulary = {}; }

window.allVocabulary["Lesson 9: Shopping - Dialogue 1 Vocabulary"] = [
    { chinese: "商店", pinyin: "shāngdiàn", pinyinNumbered: "shang1dian4", english: "store, shop" },
    { chinese: "买", pinyin: "mǎi", pinyinNumbered: "mai3", english: "to buy" },
    { chinese: "东西", pinyin: "dōngxi", pinyinNumbered: "dong1xi5", english: "things, objects" },
    { chinese: "售货员", pinyin: "shòuhuòyuán", pinyinNumbered: "shou4huo4yuan2", english: "shop assistant, salesclerk" },
    { chinese: "衣服", pinyin: "yīfu", pinyinNumbered: "yi1fu5", english: "clothes" },
    { chinese: "件", pinyin: "jiàn", pinyinNumbered: "jian4", english: "(measure word for shirts, dresses, jackets, coats, etc.)" },
    { chinese: "衬衫", pinyin: "chènshān", pinyinNumbered: "chen4shan1", english: "shirt" },
    { chinese: "颜色", pinyin: "yánsè", pinyinNumbered: "yan2se4", english: "color" },
    { chinese: "黄", pinyin: "huáng", pinyinNumbered: "huang2", english: "yellow" },
    { chinese: "红", pinyin: "hóng", pinyinNumbered: "hong2", english: "red" },
    { chinese: "穿", pinyin: "chuān", pinyinNumbered: "chuan1", english: "to wear, to put on" },
    { chinese: "裤子", pinyin: "kùzi", pinyinNumbered: "ku4zi5", english: "pants" },
    { chinese: "号", pinyin: "hào", pinyinNumbered: "hao4", english: "size" },
    { chinese: "中", pinyin: "zhōng", pinyinNumbered: "zhong1", english: "medium, middle" },
    { chinese: "便宜", pinyin: "piányi", pinyinNumbered: "pian2yi5", english: "cheap, inexpensive" },
    { chinese: "如果……的话", pinyin: "rúguǒ…de huà", pinyinNumbered: "ru2guo3…de5 hua4", english: "if" },
    { chinese: "长短", pinyin: "chángduǎn", pinyinNumbered: "chang2duan3", english: "length" },
    { chinese: "长", pinyin: "cháng", pinyinNumbered: "chang2", english: "long" },
    { chinese: "短", pinyin: "duǎn", pinyinNumbered: "duan3", english: "short" },
    { chinese: "合适", pinyin: "héshì", pinyinNumbered: "he2shi4", english: "suitable" },
    { chinese: "试", pinyin: "shì", pinyinNumbered: "shi4", english: "to try" },
    { chinese: "不用", pinyin: "búyòng", pinyinNumbered: "bu2yong4", english: "need not" },
    { chinese: "一共", pinyin: "yígòng", pinyinNumbered: "yi2gong4", english: "altogether" },
    { chinese: "多少", pinyin: "duōshao", pinyinNumbered: "duo1shao5", english: "how much/many" },
    { chinese: "钱", pinyin: "qián", pinyinNumbered: "qian2", english: "money" },
    { chinese: "块", pinyin: "kuài", pinyinNumbered: "kuai4", english: "(measure word for the basic Chinese monetary unit [equivalent of a dollar])" },
    { chinese: "毛", pinyin: "máo", pinyinNumbered: "mao2", english: "(measure word for 1/10 of a kuai [equivalent of a dime])" },
    { chinese: "分", pinyin: "fēn", pinyinNumbered: "fen1", english: "(measure word for 1/100 of a kuai [equivalent of a cent])" },
    { chinese: "百", pinyin: "bǎi", pinyinNumbered: "bai3", english: "hundred" },
    { chinese: "找 (钱)", pinyin: "zhǎo (qián)", pinyinNumbered: "zhao3 (qian2)", english: "to give change" }
];

window.allVocabulary["Lesson 9: Shopping - Dialogue 2 Vocabulary"] = [
    { chinese: "双", pinyin: "shuāng", pinyinNumbered: "shuang1", english: "(measure word for a pair)" },
    { chinese: "鞋", pinyin: "xié", pinyinNumbered: "xie2", english: "shoes" },
    { chinese: "换", pinyin: "huàn", pinyinNumbered: "huan4", english: "to exchange, to change" },
    { chinese: "一样", pinyin: "yíyàng", pinyinNumbered: "yi2yang4", english: "same, alike" },
    { chinese: "虽然", pinyin: "suīrán", pinyinNumbered: "sui1ran2", english: "although" },
    { chinese: "大小", pinyin: "dàxiǎo", pinyinNumbered: "da4xiao3", english: "size" },
    { chinese: "咖啡色", pinyin: "kāfēisè", pinyinNumbered: "ka1fei1se4", english: "brown, coffee color" },
    { chinese: "种", pinyin: "zhǒng", pinyinNumbered: "zhong3", english: "(measure word for kinds, sorts, types)" },
    { chinese: "黑", pinyin: "hēi", pinyinNumbered: "hei1", english: "black" },
    { chinese: "样子", pinyin: "yàngzi", pinyinNumbered: "yang4zi5", english: "style" },
    { chinese: "挺", pinyin: "tǐng", pinyinNumbered: "ting3", english: "very, rather" },
    { chinese: "它", pinyin: "tā", pinyinNumbered: "ta1", english: "it" },
    { chinese: "这儿", pinyin: "zhèr", pinyinNumbered: "zher4", english: "here" },
    { chinese: "刷卡", pinyin: "shuā kǎ", pinyinNumbered: "shua1 ka3", english: "to pay with a credit card" },
    { chinese: "刷", pinyin: "shuā", pinyinNumbered: "shua1", english: "to brush, to swipe" },
    { chinese: "卡", pinyin: "kǎ", pinyinNumbered: "ka3", english: "card" },
    { chinese: "收", pinyin: "shōu", pinyinNumbered: "shou1", english: "to receive, to accept" },
    { chinese: "信用卡", pinyin: "xìnyòngkǎ", pinyinNumbered: "xin4yong4ka3", english: "credit card" },
    { chinese: "不过", pinyin: "búguò", pinyinNumbered: "bu2guo4", english: "however, but" },
    { chinese: "再", pinyin: "zài", pinyinNumbered: "zai4", english: "again" },
    { chinese: "付钱", pinyin: "fù qián", pinyinNumbered: "fu4 qian2", english: "to pay money" },
    { chinese: "付", pinyin: "fù", pinyinNumbered: "fu4", english: "to pay" }
];
